// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// currency_format_
CharacterVector currency_format_(CharacterVector x, String symbol, bool symbol_first, int grouping, String decimal, String group);
RcppExport SEXP lucr_currency_format_(SEXP xSEXP, SEXP symbolSEXP, SEXP symbol_firstSEXP, SEXP groupingSEXP, SEXP decimalSEXP, SEXP groupSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type symbol(symbolSEXP);
    Rcpp::traits::input_parameter< bool >::type symbol_first(symbol_firstSEXP);
    Rcpp::traits::input_parameter< int >::type grouping(groupingSEXP);
    Rcpp::traits::input_parameter< String >::type decimal(decimalSEXP);
    Rcpp::traits::input_parameter< String >::type group(groupSEXP);
    rcpp_result_gen = Rcpp::wrap(currency_format_(x, symbol, symbol_first, grouping, decimal, group));
    return rcpp_result_gen;
END_RCPP
}
// currency_unformat_
NumericVector currency_unformat_(CharacterVector x, String decimal);
RcppExport SEXP lucr_currency_unformat_(SEXP xSEXP, SEXP decimalSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< String >::type decimal(decimalSEXP);
    rcpp_result_gen = Rcpp::wrap(currency_unformat_(x, decimal));
    return rcpp_result_gen;
END_RCPP
}
