# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

currency_format_int <- function(x, symbol, symbol_first, grouping, decimal, group) {
    .Call('rrency_currency_format_int', PACKAGE = 'rrency', x, symbol, symbol_first, grouping, decimal, group)
}

currency_format_double <- function(x, symbol, symbol_first, grouping, decimal, group) {
    .Call('rrency_currency_format_double', PACKAGE = 'rrency', x, symbol, symbol_first, grouping, decimal, group)
}

